### ISSUE TITLE
Parkour ... view upgrade = crash

### ISSUE THREAD

**Issue by AvangionQ** [pkillthetoy/tenno_mod#4]
05:49:48.581 INFO dungeons.AbstractDungeon> Removing elite: conspire:SneckoGhost from monster list.
05:49:48.583 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: NONE
05:49:48.585 INFO util.TextureLoader> InfiniteSpire | Loading Texture: img/infinitespire/monsters/nightmare/nightmare-1.png
05:49:48.616 INFO util.TextureLoader> InfiniteSpire | Loading Texture: img/infinitespire/powers/emeraldKey.png
05:49:48.627 INFO monsters.MonsterGroup> MONSTER GROUP getMonster(): Could not find monster: PondfishBoss
05:49:49.035 INFO basemod.BaseMod> publish on post power apply
05:49:49.055 INFO basemod.BaseMod> powers modified
05:49:49.118 INFO basemod.BaseMod> publish on post power apply
05:49:49.138 INFO basemod.BaseMod> powers modified
05:49:49.186 INFO basemod.BaseMod> publish on post power apply
05:49:49.203 INFO basemod.BaseMod> powers modified
05:49:49.238 INFO util.TextureLoader> InfiniteSpire | Loading Texture: img/infinitespire/monsters/nightmare/nightmare-2.png
05:49:49.255 INFO util.TextureLoader> InfiniteSpire | Loading Texture: img/infinitespire/monsters/nightmare/nightmare-3.png
05:49:49.337 INFO basemod.BaseMod> publish start battle
05:49:49.481 INFO basemod.BaseMod> publish on post power apply
05:49:49.481 INFO basemod.BaseMod> powers modified
05:49:49.827 INFO unlock.UnlockTracker> Already seen: infinitespire:FinalStrike
05:49:49.827 INFO unlock.UnlockTracker> Already seen: infinitespire:Menacing
05:49:49.859 INFO util.TextureLoader> InfiniteSpire | Loading Texture: img/infinitespire/cards/ui/512/boss-frame-attack.png
05:49:49.876 INFO util.TextureLoader> InfiniteSpire | Loading Texture: img/infinitespire/cards/ui/512/boss-frame-skill.png
05:49:50.299 INFO audio.MusicMaster> Properly faded out MENU
05:49:52.326 INFO basemod.BaseMod> publishPostDraw
Polaris Unique was drawn!=======================================
05:49:52.382 INFO basemod.BaseMod> publishPostDraw
Weak Form+ was drawn!=======================================
05:49:52.442 INFO basemod.BaseMod> publishPostDraw
Reiji was drawn!=======================================
05:49:52.506 INFO basemod.BaseMod> publishPostDraw
Apotheosis was drawn!=======================================
05:49:52.567 INFO basemod.BaseMod> publishPostDraw
Requiem was drawn!=======================================
05:49:52.622 INFO basemod.BaseMod> publish on post power apply
05:49:52.632 INFO basemod.BaseMod> powers modified
05:49:52.701 INFO basemod.BaseMod> publish on post power apply
05:49:52.719 INFO basemod.BaseMod> powers modified
05:49:52.785 INFO basemod.BaseMod> publish on post power apply
05:49:52.798 INFO basemod.BaseMod> powers modified
05:49:58.165 INFO util.TextureLoader> InfiniteSpire | Loading Texture: img/infinitespire/cards/ui/512/boss-frame-power.png
05:50:07.882 INFO input.InputHelper> LEAVING CONTROLLER MODE
Finding texture: img/cards/Power_p.png
Entering controller mode: BUTTON pressed
Exception: java.lang.NullPointerException
05:50:10.848 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.cards.AbstractCard.initializeDescription(AbstractCard.java:452) ~[?:?]
	at tenno_mod.cards.uncommon.Parkour_TENNO.upgrade(Parkour_TENNO.java:57) ~[tenno_mod.TennoMod.jar:?]
	at conspire.relics.InfiniteJournal.upgradeCard(InfiniteJournal.java:58) ~[Conspire.jar:?]
	at com.megacrit.cardcrawl.screens.SingleCardViewPopup.render(SingleCardViewPopup.java:335) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:462) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by pkillthetoy** [comment]
Well thankfully this one is easy. It's been fixed in the latest release. Thanks for the quick catch.
